ufmg-smite/carcara

carcara/src/ast/printer.rs

Sets print with sharing as the default implementation for terms due to the fact that terms can grow exponentially and lead to timeouts and unnecessary time spending.
> Signed-off-by: Vinícius Braga Freire [vinicius.braga.freire@gmail.com](mailto:vinicius.braga.freire@gmail.com)

Set print with sharing as default for terms

---

carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR adds the `concat_conflict` rule from the Strings theory.
Rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule15CONCAT_CONFLICTE) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/3d249fa410d350d418e68f893fe175f80ab9ce10/proofs/alf/cvc5/rules/Strings.smt3#L67-L94).

[rules] [strings] Adds the `concat_conflict` rule and unit tests

---

carcara/src/ast/macros.rs
carcara/src/ast/mod.rs
carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/extras.rs
carcara/src/checker/rules/strings.rs

This PR adds the `concat_csplit` rule from the Strings theory.
Rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule13CONCAT_CSPLITE) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/3d249fa410d350d418e68f893fe175f80ab9ce10/proofs/alf/cvc5/rules/Strings.smt3#L48-L65).

[rules] [strings] Add support for `concat_csplit` rule

---

carcara/src/ast/macros.rs
carcara/src/ast/mod.rs
carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR adds the `concat_csplit` rule from the Strings theory.
Rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule12CONCAT_SPLITE) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/14eae04ec806140aa8e92293b69b2ca7a251d895/proofs/alf/cvc5/rules/Strings.smt3#L68-L95).
Furthermore, it:
* Splits the rule into two versions: application over prefixes and over suffixes;
* Makes the necessary modifications to allow other rules to be split in this way;
* Standardizes variable names to how they appear in AletheLF documentation;
* Fixes a bug in the function that creates Skolems in the `concat_csplit` rule.

[rules] [strings] Add support for `concat_split` rule and splitted rules in prefix and suffix version

---

carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR splits the `concat_csplit` rule into a prefix version and a suffix version.
The main reason for this modification is to simplify how the rule works, since it's premises and conclusion changes substantially based on the reverse parameter value (if the parameter is set to `true`, the rule is reasoning about suffixes, and if it's set to `false`, about prefixes).
All unit tests where converted and some additional cases where incorporated to cover previously untested scenarios.
The rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule13CONCAT_CSPLITE) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/231c532981c71e0b450d6bfc238c922a36233282/proofs/alf/cvc5/rules/Strings.smt3#L49 …

[rules] [strings] Splits `concat_csplit` rule into prefix and suffix versions

---

carcara/src/ast/context.rs
carcara/src/ast/mod.rs
carcara/src/ast/printer.rs
carcara/src/checker/rules/bitvectors.rs
carcara/src/elaborator/accumulator.rs
carcara/src/elaborator/mod.rs
carcara/src/elaborator/polyeq.rs
carcara/src/parser/mod.rs

This is necessary to fix a bug (introduced in
ce9d5e54099e209f74fca784d31a05b1cc1a619c) where elaborated proofs will not be checkable by Carcara itself (since the printer was not printing anchors according to the new format).

Use SortedVar rather than String for vars in anchor assingnments

---

carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR adds the `concat_lprop` rule from the Strings theory.
Rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule12CONCAT_LPROPE) (at the time of writing this PR, the rule still hasn't been updated to align with its definition in AletheLF) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/b4189cace4535142969d7eee50894e8ccb65c73c/proofs/alf/cvc5/rules/Strings.smt3#L97-L119).

[rules] [strings] Add support for `concat_lprop` rule

---

carcara/src/ast/printer.rs

The names used for `declare-sort` and `define-fun` are symbols that can be quoted.

Fix prelude printing

---

carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR adds the `concat_cprop` rule from the Strings theory.
Rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule12CONCAT_CPROPE) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/942f4bac8da99fa84d2629f076dce64908026d6e/proofs/alf/cvc5/rules/Strings.smt3#L122-L143).

[rules] [strings] Add support for `concat_cprop` rule

---

carcara/src/checker/mod.rs
carcara/src/checker/parallel/scheduler.rs
carcara/src/checker/rules/extras.rs
carcara/src/checker/rules/transitivity.rs

This is because it doesn't actually use the `or` operator. Instead it operates directly on the clause.
See the conversation here:
https://gitlab.uliege.be/verit/alethe/-/issues/45

Rename `or_intro` rule to `weakening`

---

carcara/src/ast/mod.rs
carcara/src/ast/polyeq.rs
carcara/src/ast/tests.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs
carcara/src/elaborator/polyeq.rs

This PR adds the `string_decompose`, `string_length_pos` and `string_length_non_empty` rules from the Strings theory.
Rules reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/proofs/proof_rules.html#_CPPv4N4cvc59ProofRule16STRING_DECOMPOSEE) and in the [AletheLF specification](https://github.com/cvc5/cvc5/blob/994c86b5dc4cc6d3a54f9fc1cdda593fd9372012/proofs/alf/cvc5/rules/Strings.smt3#L7-L17).
Furthermore, it extends the `PolyeqComparator` to properly reason over String concatenations and String constants. This extension allows semantically equal Strings, such as `(str.++ "a" "b")` and `"ab"`, to be identified as equal by the comparator.

[rules] [strings] Add support for the String length core rules and extend `PolyeqComparator` for String comparisons

---

carcara/src/ast/node.rs
carcara/src/ast/polyeq.rs
carcara/src/ast/printer.rs
carcara/src/ast/proof.rs
carcara/src/checker/error.rs
carcara/src/checker/rules/linear_arithmetic.rs
carcara/src/checker/rules/mod.rs
carcara/src/checker/rules/quantifier.rs
carcara/src/checker/rules/resolution.rs
carcara/src/checker/rules/strings.rs
carcara/src/elaborator/mod.rs
carcara/src/elaborator/reordering.rs
carcara/src/elaborator/resolution.rs
carcara/src/elaborator/transitivity.rs
carcara/src/elaborator/uncrowding.rs
carcara/src/parser/mod.rs
carcara/src/parser/tests.rs

The main impact is that ProofArg is removed and everything is made more uniform
since arguments are only terms.

Update for arguments being only terms

---

carcara/src/ast/macros.rs
carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR adds the `re_inter`, `re_unfold_neg` and `re_unfold_neg_concat_fixed` rules from the Strings theory.
For simplification reasons, the `re_unfold_neg_concat_fixed` rule was splitted in a prefix version and suffix version (resp. `re_unfold_neg_concat_fixed_prefix` and `re_unfold_neg_concat_fixed_suffix`), just like it was done for other previously implemented rules.
Future PR's will add the `re_unfold_pos` rule.
Rules reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/api/cpp/enums/proofrule.html#_CPPv4N4cvc59ProofRule8RE_INTERE) and in the [CPC specification](https://github.com/cvc5/cvc5/blob/973ec555d552c7e0d0747308f18498f9838327e2/proofs/eo/cpc/rules/Strings.eo#L314-L416).

[rules] [strings] Add support for some core Strings theory rules that reason about Regular expressions

---

carcara/src/ast/term.rs
carcara/src/checker/error.rs
carcara/src/checker/rules/clausification.rs
carcara/src/checker/rules/tautology.rs

The semantics of the rules `and`, `not_or`, `and_pos`, and `or_neg` changed so that now they expect an argument as to the position in which the concluding element is from an n-ary application of the operators `and` or `or`.

[rules] [clausification, tautologies] Support for arguments

---

carcara/src/checker/rules/tautology.rs

Fix small bug in checking of connective_def if the connective is forall

---

carcara/src/ast/macros.rs
carcara/src/ast/polyeq.rs
carcara/src/ast/pool/mod.rs
carcara/src/ast/term.rs
carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/drup.rs
carcara/src/checker/rules/mod.rs
carcara/src/drup.rs
carcara/src/lib.rs
carcara/src/parser/mod.rs

This PR adds DRAT and optionally DRUP checking rules. 
The rule is represented by:
`(step t4 (cl a) :rule drup :premises (t0 t1 t2) :args ((cl a b)))` or
`(step t4 (cl a) :rule drat :premises (t0 t1 t2) :args ((cl a b)))
`
Where args is the implied clause as usual.

Drat and Drup checking

---

carcara/src/checker/mod.rs
carcara/src/checker/rules/cutting_planes.rs
carcara/src/checker/rules/mod.rs
carcara/src/parser/error.rs

This PR introduces the initial declarations for cutting planes rule checkers and includes their corresponding unit tests.
- Added empty function stubs for cutting planes rules:
1. `cp_addition`
2. `cp_multiplication`
3. `cp_division`
4. `cp_saturation`
Also stubs for unit tests for each rule are defined and will be used to validate the implementation. Once the checker functions are fully implemented in subsequent PRs.
Note: The checker functions are currently empty and just return `Err(CheckerError::Unspecified)`. This PR focuses on establishing the framework and test coverage

Add Cutting Planes Rule Checkers and Unit Tests

---

carcara/src/checker/mod.rs
carcara/src/checker/rules/mod.rs
carcara/src/checker/rules/pb_blasting.rs
carcara/src/parser/error.rs

This PR introduces the initial declarations for PBBlast rule checkers.
- Added empty function stubs for PBBlast rules covering various operations:
- **Equality and Comparisons**:
- `pbblast_bveq`, `pbblast_bvult`, `pbblast_bvugt`, `pbblast_bvuge`, `pbblast_bvule`
- Signed variants: `pbblast_bvslt`, `pbblast_bvsgt`, `pbblast_bvsge`, `pbblast_bvsle`
- **Core Blasting**:
- `pbblast_pbbvar` (bitvector variables)
- `pbblast_pbbconst` (constants)
- **Bitwise Operations**:
- `pbblast_bvxor` (XOR)
- `pbblast_bvand` (AND)
Unit tests for each rule will be implemented and will be used to validate the implementation once the checker functions are fully developed in subsequent PRs.
Note: All checker functions currently return `Err(CheckerError::Unspecified)` as placeholders. This PR focuses on setting …

Add PBBlast Rule Checkers (empty)

---

carcara/src/checker/rules/pb_blasting.rs

This PR adds the implementation of the pbblast_bveq rule for checking equality between bitvectors using pseudo-Boolean blasting. 
- Implements **pbblast_bveq** to validate equality of bitvectors by comparing their corresponding summations.
- Adds helper functions _check_pbblast_sum_ and _check_pbblast_constraint_ for structural validation of the blasted terms.
- Includes extensive test cases covering:
- 1-bit, 2-bit, and 8-bit bitvectors
- Valid encodings and malformed patterns (e.g., wrong coefficients, incorrect constants)
- Support for both explicit and **implicit** coefficients

Implement the rule `pbblast_bveq`

---

carcara/src/checker/rules/cutting_planes.rs

This PR implements the `cp_saturation` rule checker for cutting planes proofs with comprehensive validation logic.
- Added `cp_saturation` checker that:
- Reuses the helper functions
- Ensures conclusion matches minimum between premise and the constant
- Change the addition tests and `unwrap_pseudoboolean_inequality` to account for a summation list of two elements or more differently than a single term (no summation)

Implement Cutting Planes Saturation Rule Checker (`cp_saturation`)

---

carcara/src/checker/rules/cutting_planes.rs

This PR implements the `cp_multiplication` rule checker for cutting planes proofs with comprehensive validation logic.
- Added `cp_multiplication` checker that:
- Reuses the helper functions
- Ensures conclusion matches reduced premise combination times scalar
- Depends on #63

Implement Cutting Planes Multiplication Rule Checker (`cp_multiplication`)

---

carcara/src/checker/rules/cutting_planes.rs

This PR implements the `cp_division` rule checker for cutting planes proofs with comprehensive validation logic.
- Added `cp_division` checker that:
- Reuses the helper functions
- Ensures conclusion matches ceiling division of premise by the scalar
- Depends on #63

 Implement Cutting Planes Division Rule Checker (`cp_division`)

---

carcara/src/checker/rules/pb_blasting.rs

This PR adds the implementation of the pbblast_pbbvar rule for checking the pseudo-boolean bit blasting of a bitvector variable. 
- Tests for 1, 2 and 8 bits were created, covering indexing and ordering of the bits
- The semantics for this rule are in page 56, rule 114 of [WIP alethe docs](https://gitlab.uliege.be/verit/alethe/-/jobs/188683/artifacts/raw/specification.pdf?inline=false)

Implement PBBlast `pbblast_pbbvar` rule

---

carcara/src/ast/polyeq.rs

This is to further handle differences between assertions and assumptions containing `(/ 1 2)` vs `1/2` for example, but involving negations and whatnot.

[polyeq] Updates to handle rational constants

---

carcara/src/checker/error.rs
carcara/src/checker/mod.rs
carcara/src/checker/rules/strings.rs

This PR adds the `re_unfold_pos` rule from the Strings theory. More than that, this PR also splits the reasoning previously handled by a single rule into two distinct rules: `re_concat_unfold_pos` and `re_kleene_star_unfold_pos`. This was done to distinguish two behaviors that are notably different but were being implemented within the same rule. With this separation, even though the rules still share some logic and reasoning, it becomes clearer what each of them is doing specifically.
Rule reference can be found in the [cvc5 documentation](https://cvc5.github.io/docs-ci/docs-main/api/cpp/enums/proofrule.html#_CPPv4N4cvc59ProofRule13RE_UNFOLD_POSE) and in the [CPC specification](https://github.com/cvc5/cvc5/blob/c56a15e30823c8360d7d7498d42db66d9c879f1d/proofs/eo/cpc/rules/Strings.eo#L299-L …

[rules] [strings] Add support for `re_unfold_pos` rule

---

carcara/src/checker/rules/pb_blasting.rs

This PR adds the implementation of the `pbblast_bvugt` rule for checking *unsigned* pb bit blasted > operation.
- Its similar to the `pbblast_bvult` rule but we swapped the $x$ and $y$ sides
- Depends on #70

Implement the rule `pbblast_bvugt`

---

carcara/src/checker/error.rs
carcara/src/checker/rules/pb_blasting.rs

- Extend the unsigned and signed checker methods for short-circuit applications
- Add short-circuit variations for each relational rule, signed and unsigned
- Fix typo in checker error

Extend Pseudo-Boolean relational operations with short-circuit

---

carcara/src/checker/mod.rs
carcara/src/checker/rules/cutting_planes.rs
carcara/tests/rules/cutting_planes.rs

Implementation of the rule `cp_literal`, described [here](https://gitlab.uliege.be/verit/alethe/-/jobs/196565/artifacts/browse), page 54. "A literal 𝑙 being greater or equal to zero can be introduced at any time"
This rule is true when we suppose $l$ is either a pseudo boolean variable or the negation of one `(- 1 l)`

Implement rule `cp_literal`

---

carcara/src/checker/rules/cutting_planes.rs
carcara/tests/rules/cutting_planes.rs

While using the rule `cp_normalize` I realized the length of the variables list was not being validated, what introduced issues if variables of the left hand side are omitted in the right hand side. 
In this sense I added tests to check the behavior and the fix in the `check_pb_inequalities` helper method.

Patch: Validate vars list length in `check_pb_inequalities`

---

carcara/src/checker/mod.rs
carcara/tests/test_proof.rs

Currently Carcara would accept a proof like this:
```
...
(anchor :step t0)
(step t0.t1 (cl) :rule hole)
(step t0 (cl false) :rule subproof)
```
The issue is that the check of whether a step concluding the empty clause has been reached is not guarding to having happened only in the context of a subproof. So it is currently possible to have a valid (or holey) refutation of a given input without deriving the empty clause from it but rather only in a subproof, with other assumptions.
@bpandreotti I wanted to add a test like the proof above, but I was uncertain how. Any suggestions?

Avoid subproofs concluding empty clause to confuse valid refutation check
